name = "black-bot"
main = "src/index.ts"
compatibility_date = "2025-05-15"

[[kv_namespaces]]
binding = "USER_DATA"
id = "f812f1ba44ef48e8afb65af31185f806"

[env.production]
vars = { BOT_TOKEN = "", REQUIRED_CHANNEL = "BlackArsenalStore" }
